### ISSUE TITLE
Value can not be shown.

### ISSUE THREAD

**Issue by LhiKien** [Will-tm/WMGaugeView#24]
![snapshot](https://cloud.githubusercontent.com/assets/6253031/7223328/18315f8c-e752-11e4-8b1f-fa5d22847d92.png)

**Comment by kaishin** [comment]
Yes, I'm encountering the same issue.

**Comment by kaishin** [comment]
Solved it by adding:

`gaugeView.showScale = YES;`

**Comment by LhiKien** [comment]
Thanks for your comment.
